spring:
  application: name:"shopapp"
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
server:
  port: 8088
# spring:
#   datasource:
#     url="jdbc:oracle:thin:@localhost:1521:orcl"
#     username="apps"
#     password="apps"
